### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by matinaz** [buraktahap/Studio_Reservation_App#1]
Hello!

I want to ask if this app is connected to a database, in order the gym to make the management of the classes, users etc?
Additionally, could you please help me in order to run the code and build the app? Can you give some instructions?

**Comment by buraktahap** [comment]
Hi!

You can check the backend of this repo here: https://github.com/buraktahap/StudioReservationAPP-Backend . I was working with the local databases. After you created the tables with the backend project, you might need to create some dummy data manually as the project doesn't contain all of the CRUD methods for all classes. 

Good luck!
